import { IMAGE_SIZE_CAROUSEL_BANNER, IMAGE_SIZE_PRODUCT_LISTING } from '@/libs/data';

export const IMAGE_SIZE_VARIANTS = {
    PRODUCT_LISTING: 'product-listing',
    CAROUSEL_BANNER: 'carousel-banner',
} as const;

export const IMAGES_SIZE_HANDLES = {
    [IMAGE_SIZE_VARIANTS.PRODUCT_LISTING]: IMAGE_SIZE_PRODUCT_LISTING,
    [IMAGE_SIZE_VARIANTS.CAROUSEL_BANNER]: IMAGE_SIZE_CAROUSEL_BANNER,
};
