import { SUPABASE_HEADER_CATEGORIES, SUPABASE_HEADER_NAVIGATION, SUPABASE_HEADER_PAGES } from '@/libs/data';

export const SUPABASE_VARIANTS = {
    NAVIGATION: 'navigation',
    CATEGORIES: 'categories',
    PAGES: 'pages',
} as const;

export const SUPABASE_HANDLES = {
    [SUPABASE_VARIANTS.NAVIGATION]: 'Navigation',
    [SUPABASE_VARIANTS.CATEGORIES]: 'Categories',
    [SUPABASE_VARIANTS.PAGES]: 'Pages',
};

export const SUPABASE_HEADER_HANDLES = {
    [SUPABASE_VARIANTS.CATEGORIES]: SUPABASE_HEADER_CATEGORIES,
    [SUPABASE_VARIANTS.NAVIGATION]: SUPABASE_HEADER_NAVIGATION,
    [SUPABASE_VARIANTS.PAGES]: SUPABASE_HEADER_PAGES,
};
